README.md
Add LoFloccus companion app as discussed at https://github.com/marcelklehr/floccus/issues/240.
=> Add LoFloccus companion app

views/options.html
=> Added font color as black

src/lib/SyncProcess.js
=> SyncProcess: Only sync bookmark if they really differ

_locales/en/messages.json, src/lib/Account.js, src/lib/Tree.ts, src/lib/strategies/Default.ts, src/test/test.js, src/ui/components/AccountCard.vue, src/ui/components/OptionFailsafe.vue, src/ui/components/OptionsNextcloudFolders.vue, src/ui/components/OptionsWebdav.vue
Don't remove more than 50% of local bookmarks by default
=> Implement failsafe

.github/workflows/build.yml, .github/workflows/tests.yml, .gitignore, _locales/en/messages.json, gulpfile.js, manifest.json, src/lib/Account.js, src/lib/adapters/Caching.ts, src/lib/adapters/GoogleDrive.ts, src/lib/adapters/WebDav.js, src/lib/interfaces/Adapter.ts, src/test/test.js, src/ui/components/OptionsGoogleDrive.vue, src/ui/views/AccountOptions.vue, src/ui/views/NewAccount.vue, test/selenium-runner.js, tsconfig.json
=> Implement Google Drive sync

_locales/en/messages.json, src/lib/adapters/NextcloudFolders.ts, src/lib/adapters/WebDav.js, src/ui/components/AccountCard.vue, src/ui/components/OptionClientCert.vue, src/ui/components/OptionsNextcloudFolders.vue, src/ui/components/OptionsWebdav.vue
=> New option: {WebDAV, Nextcloud} Allow sending client-cert in options

_locales/en/messages.json, src/lib/LocalTree.ts, src/lib/strategies/Default.ts, src/lib/strategies/Merge.ts, src/lib/strategies/Unidirectional.ts, src/lib/strategies/UnidirectionalMerge.ts, src/test/test.js
=> Extend tests for and fix unidirectional sync strategy

src/lib/adapters/NextcloudFolders.ts, src/lib/interfaces/Resource.ts, src/lib/strategies/Default.ts
=> Speedup loading new folders in NextcloudFolders

src/ui/store/actions.js
=> Sync root folder by default

src/lib/Account.js, src/lib/Controller.js
=> Sync: Invalidate cache after sync error

src/lib/strategies/Default.ts, src/test/test.js
fixes #797
also influences #186
=> Only remove duplicates for Nextcloud

src/test/test.js
=> Tests: Add test for deletions not breaching server folder boundaries

html/options.html, src/ui/App.vue, src/ui/plugins/vuetify.js, src/ui/views/Overview.vue
=> Use dark theme if enabled

src/lib/adapters/NextcloudFolders.ts, src/lib/strategies/Merge.ts, src/test/test.js
=> Add test for and fix serverRoot breach

src/lib/strategies/Default.ts
faulty seed was `0.30598971705880507`
=> Fix syncing inconsistency

src/lib/strategies/Default.ts, src/test/test.js
=> Fix another complex hierarchy reversal

src/lib/Scanner.ts
there's code to handle this situation after all
=> Scanner: Do not avoid REORDERs when moving items

.github/workflows/tests.yml, src/lib/adapters/GoogleDrive.ts, src/lib/adapters/WebDav.js, src/test/index.js, src/test/test.js
As a softer, smarter measure before implementing #1068
=> Implement timed locks

src/lib/adapters/Caching.ts, src/lib/strategies/Default.ts
=> Sync chrome:// URLs (but not on Firefox)

doc/Adapters.md
=> Docs: Fix typo

src/lib/LocalTabs.ts, src/test/test.js
=> Write tests for tab sync

src/lib/browser/BrowserTree.ts, src/test/test.js
=> Separators: More than one separator per Folder on Nc Bookmarks

ios/App/App/Info.plist, src/lib/adapters/GoogleDrive.ts
=> GoogleDrive: Implement native http methods

src/lib/adapters/GoogleDrive.ts
Fixes #1236
Sorry for the delay, everyone :v:
=> Fix Google Drive on native

src/ui/components/OptionsWebdav.vue, src/ui/views/NewAccount.vue
=> Fix selecting HTML at setup

src/lib/Mappings.ts, src/lib/Scanner.ts, src/lib/browser/BrowserTree.ts
=> Don't cast item IDs to boolean inside if statements

src/lib/Tree.ts, src/lib/adapters/Caching.ts
This should fix #1329, but I haven't tested it because I have nothing set up to do it.
Let me know what you think :wink:
=> Added 'file:' protocol to STRANGE_PROTOCOLS and CachingAdapter.acceptsBookmark

src/lib/adapters/Git.ts, src/lib/adapters/GoogleDrive.ts, src/lib/adapters/NextcloudBookmarks.ts, src/lib/adapters/WebDav.ts
=> fix: Don't set lock after freeing it

src/lib/adapters/Git.ts
=> fix(Git): Don't ever bulldoze the repository

src/lib/adapters/GoogleDrive.ts, src/lib/adapters/WebDav.ts
=> fix(GoogleDrive,WebDAV): Allow passing salt in file contents

src/test/test.js
=> test: Should sync empty folders

src/lib/adapters/GoogleDrive.ts, src/lib/adapters/WebDav.ts
To be merged 1 month after af25b7098fad9fa05a57b78024d299f345731707 has been published
=> fix(WebDav, GoogleDrive): Use new encryption

src/test/test.js
https://github.com/floccusaddon/floccus/issues/1751
=> test: ampersand in URLs should be stable

src/lib/Scanner.ts, src/lib/Tree.ts, src/lib/strategies/Merge.ts, src/lib/strategies/Unidirectional.ts, src/test/test.js
see https://github.com/floccusaddon/floccus/issues/1681
=> Move stability with same-titled folders

_locales/de/messages.json, _locales/en/messages.json, _locales/fi/messages.json, _locales/fr/messages.json, _locales/gl/messages.json, _locales/ja/messages.json, _locales/tr/messages.json, _locales/zh/messages.json, _locales/zh_CN/messages.json, src/errors/Error.ts
Original commit that pasted E036 instead is from May 11, 2024.
=> Fix copy/paste typos for E037 & E038 error messages.

src/lib/serializers/Xbel.ts
=> fix(Xbel): Don't parse tag values

src/lib/LocalTabs.ts
Reduces the chances of #1857 happening
=> fix(LocalTabs): Speed up tabs updated callback

src/lib/Account.ts
Signed-off-by: Marcel Klehr <mklehr@gmx.net>
=> fix: Don't call onSyncFail twice

src/lib/browser/BrowserTree.ts
see https://developer.chrome.com/blog/bookmarks-sync-changes
=>  fix(BrowserTree): Do not guess bookmark folders' ids 

_locales/en/messages.json, src/errors/Error.ts, src/lib/adapters/Git.ts, src/lib/browser/BrowserAccount.ts, src/lib/native/NativeAccount.ts
=> fix(Git): catch errors from git.push operations

.github/workflows/tests.yml, manifest.chrome.json, manifest.firefox.json, src/lib/LocalTabs.ts, src/lib/Scanner.ts, src/lib/strategies/Default.ts, src/test/test.js, test/selenium-runner.js
=> feat(TabGroups): Allow syncing tab groups

src/lib/adapters/Linkwarden.ts
instead of the links endpoint
fixes #2011
=> fix(Linkwarden): Switch to new search endpoint
