floccusaddon/floccus

src/lib/AccountStorage.js
src/lib/Controller.js

This PR  reverts some changes from da085e0 and 5739a5c.

Replace localforage with browser extension storage. Fixes #459

---

src/entries/native.js
src/entries/options.js
src/lib/native/I18n.ts
src/ui/index.js
src/ui/native.js

- Fix loading languages with hyphens
- Fix async loding languages
I tested in chrome on windows system and the language loads correctly.
But not tested on android because I won't package as apk.
I have doubts about whether the language will load correctly on Android.
Because the documentation of `@capacitor/device` describes that `getLanguageCode()` returns a value of `Two character language code.`, so `zh-CN` will return `zh`?
If so, that won't load Simplified Chinese correctly, because there is no `zh` in the translation, only `zh-CN` and `zh-TW`, and they won't be loaded.

Fix loading locale

---

.github/ISSUE_TEMPLATE/bug_report.yml

Clarify wording that "exact version" does not mean saying "latest", as that is ambiguous (depending on different browser stores, caches, betas, when the issue was created and when it actually gets looked at, etc).

Update bug_report.yml text

---

src/ui/views/native/Tree.vue

L337: add toLowerCase() to the sortBy method
fixes #1189

Fix Alphabetical sorting issue in Tree.vue

---

src/ui/components/AccountCard.vue

Sync icon and merge icon are the same. To avoid confusion, I propose to replace by an icon representing two arrows merging.

Replace merge icon to avoid confusion with sync icon

---

src/lib/adapters/WebDav.ts

This should fix #956, but haven't tested because I have nothing set up to do it.

No cache for WebDAV downloadFile* functions

---

README.md
package-lock.json
package.json
webpack.common.js

closes #1284
Remove dependency "fibers", which does not work with node 16 and above - see https://github.com/laverdet/node-fibers#readme.
Disable use of "fibers" in "sass-loader" according to https://webpack.js.org/loaders/sass-loader/#string.
Update instructions to setup development environment in README. It should be possible to build the project with nodejs 18 (current LTS version) now.
I've tried `npm run build` and `npm run watch`, and both succeeded with out errors. I haven't tried actually running the project in Android Studio, for example.

Support Node v18 for build

---

_locales/en/messages.json
manifest.json
src/errors/Error.ts
src/lib/Account.ts
src/lib/adapters/GoogleDrive.ts
src/lib/adapters/NextcloudBookmarks.ts
src/lib/adapters/WebDav.ts
src/lib/browser/BrowserController.js
src/lib/interfaces/Controller.ts
src/lib/native/NativeController.js
src/test/test.js
src/ui/components/AccountCard.vue
src/ui/views/Overview.vue
src/ui/views/native/Tree.vue

refactor: Move waiting for lock out of adapters into controller

---

src/lib/serializers/Html.ts
src/test/test.js

fix: Encode unsafe characters as HTML entities

---

src/lib/adapters/GoogleDrive.ts
src/test/test.js

fix(GoogleDrive): Sort files by modified date

---

src/lib/Account.ts
src/lib/LocalTabs.ts
src/lib/browser/BrowserController.js
src/lib/strategies/Default.ts
src/test/test.js

Make merge strategy work with tabs

---

src/lib/strategies/Default.ts
src/test/test.js

NC Bookmarks cannot handle URL collisions
see #1804

fix: Don't produce UPDATE when URL changes

---

src/ui/views/native/AddBookmarkIntent.vue

This is another part of https://github.com/floccusaddon/floccus/issues/1826 . Just like in the Edit dialog, avoid saving a newly-shared bookmark if its URL is invalid.

Prevent saving a newly-added bookmark if the URL is bad

---

src/ui/views/native/Tree.vue

This is a part of https://github.com/floccusaddon/floccus/issues/1826 - avoid the app crashing when we find an invalid URL has made its way into the list.

Catch and log any errors we encounter when parsing a URL to display its hostname

---

src/ui/views/native/AddBookmarkIntent.vue

This is a part of addressing https://github.com/floccusaddon/floccus/issues/1826 - make sure that we display an error message in the Add Bookmark dialog immediately, if the shared URL is bad.
Before this change, there would be no error message in the "Add Bookmark" screen until we edited the URL, but now the error appears immediately:
I have zero Vue experience, so please let me know if I did it wrong.

Check that a URL is valid as soon as we load the Add Bookmark dialog

---

src/ui/views/native/Home.vue

Fixes #1826 .
Look for a URL at the end of a long string of title+URL passed to us from `SendIntent`. It's possible a better fix might be available by modifying `SendIntent` (or even by asking for a fix to the Amazon Shopping app?) but this makes things work as they should, and doesn't do anything if we are given a valid URL, so hopefully can't do much harm even if this is later fixed upstream.
Before:
After:

Try to find a valid URL when an app shares title+URL stuffed together

---

manifest-firefox-override.sh

Thank you for Floccus. Hoping to contribute more.
You as an author of Floccus may have some more advanced setup that avoids the below problem, but for most developers (even ones with experience of developing Firefox extensions), the problem described below is a big time waster/accident maker. Hoping the workaround script is clear.
If you know of any more mistake/me-the-local-idiot-proof setup with less work or more reproducible/automated, I'm open to alternatives.
(Also in `manifest-firefox-override.sh`:)
Local development workaround for Firefox.
Once you build this extension (with `npm install` and `npm run build`, as per <README.md>), to load it, visit Firefox special URL about:debugging#/runtime/this-firefox. Click button "Load Temporary Add-on..." That button shows a file/folder …

script to override manifest.json for Firefox and prevent accidental GIT commits

---

README.md

While recently working on the vertical separators in the Bookmarks Toolbar I spent a bunch of time figuring out how to   
correctly build the browser extension under Windows,  
how to load it into my local browser,  
and how to execute the test suite.
This PR summarizes my learnings in the ReadMe file, so that future contributors have an easier time getting started.

Add ReadMe sections on Windows and on running browser extension tests locally.

---

src/lib/browser/BrowserController.js
src/lib/native/NativeController.js

Signed-off-by: Marcel Klehr <mklehr@gmx.net>

fix: Cap exponential backoff at 1h

---

_locales/en/messages.json
src/errors/Error.ts
src/lib/adapters/WebDav.ts

fix(webdav): Validate filesize via PROPFIND to detect partial downloads

---

_locales/en/messages.json
src/errors/Error.ts
src/lib/browser/BrowserAccount.ts
src/lib/native/NativeAccount.ts
src/lib/strategies/Default.ts
src/lib/strategies/Unidirectional.ts
src/test/test.js

feat(AdditionFailsafe): Extend failsafe mechanism to prevent creation of excessive amounts of bookmarks
